name: 'Trebuchet-Action'
description: 'The purpose of Trebuchet is to improve the quality of life for pushing Docker images to Amazon Elastic Container Registry (ECR).  The action assumes that you''ve set up your AWS credentials using the AWS credentials action.'
author: 'HylandSoftware'
inputs:
  action: 
    required: true
    description: 'The command to execute, `push` or `copy` are the currently supported actions.'
  region: 
    required: false
    description: 'The AWS region to execute against.  It will use this property or pull from the AWS_DEFAULT_REGION Environment variable.'
    default: ''
  source-account-id:
    required: false
    description: 'The account id of the source AWS account for a pull / copy, if different than the default account id.'
    default: ''
  source-role-arn:
    required: false
    description: 'The role arn to use when pulling the image from ECR.  Only needed when the source role is different from the default environment credentials.'
    default: ''
  repository: 
    required: false
    description: 'The name of the image in either the local docker or remote registry. Mutually exclusive with repositories.'
    default: ''
  repositories: 
    required: false
    description: 'The names of the images in either the local docker or remote registry separated by a new line.  Mutually exclusive with repository.'
    default: ''
  tag: 
    required: true
    description: 'The tag of the image to use when performing the action'
  immutable:
    required: false
    description: 'Whether the repository should be created as IMMUTABLE (if not already existing)'
    default: 'false'
outputs:
  registry:
    description: 'The URI of the ECR registry i.e. aws_account_id.dkr.ecr.region.amazonaws.com'

runs:
  using: 'node16'
  main: 'dist/index.js'
